
# Gem::Specification for Validates_email_format_of-1.2.1
# Originally generated by Echoe

--- !ruby/object:Gem::Specification 
name: validates_email_format_of
version: !ruby/object:Gem::Version 
  version: 1.2.1
platform: ruby
authors: 
- Alex Dunae
autorequire: 
bindir: bin

date: 2008-07-01 00:00:00 -04:00
default_executable: 
dependencies: 
- !ruby/object:Gem::Dependency 
  name: echoe
  type: :development
  version_requirement: 
  version_requirements: !ruby/object:Gem::Requirement 
    requirements: 
    - - ">="
      - !ruby/object:Gem::Version 
        version: "0"
    version: 
description: Validate e-mail addreses against RFC 2822 and RFC 3696
email: code@code.dunae.ca
executables: []

extensions: []

extra_rdoc_files: 
- CHANGELOG
- lib/validates_email_format_of.rb
- README
files: 
- CHANGELOG
- init.rb
- lib/validates_email_format_of.rb
- MIT-LICENSE
- rails/init.rb
- rakefile
- README
- test/database.yml
- test/fixtures/people.yml
- test/fixtures/person.rb
- test/schema.rb
- test/test_helper.rb
- test/validates_email_format_of_test.rb
- Rakefile
- Manifest
- validates_email_format_of.gemspec
has_rdoc: true
homepage: http://code.dunae.ca/validates_email_format_of.html
post_install_message: 
rdoc_options: 
- --line-numbers
- --inline-source
- --title
- Validates_email_format_of
- --main
- README
require_paths: 
- lib
required_ruby_version: !ruby/object:Gem::Requirement 
  requirements: 
  - - ">="
    - !ruby/object:Gem::Version 
      version: "0"
  version: 
required_rubygems_version: !ruby/object:Gem::Requirement 
  requirements: 
  - - "="
    - !ruby/object:Gem::Version 
      version: "1.2"
  version: 
requirements: []

rubyforge_project: validates_email_format_of
rubygems_version: 1.2.0
specification_version: 2
summary: Validate e-mail addreses against RFC 2822 and RFC 3696
test_files: 
- test/test_helper.rb
- test/validates_email_format_of_test.rb
